<?php

namespace App\Command;

/**
 * Provides medal command metadata and classifications.
 */
class StatMedalCatalog
{
    /**
     * Get medal command mappings.
     */
    public static function mapping(): array
    {
        return [
            'hurricane' => 'medalAbilityFlowwalkerMulti',
            'handfullofbullets' => 'medalAbilityGunslingerMulti',
            'lethalinstinct' => 'medalAbilityGunslingerQuick',
            'lightningstorm' => 'medalAbilityStormcallerMulti',
            'bloodforblood' => 'medalAvenger',
            'iliveherenow' => 'medalControlAdvantageHold',
            'flagbearer' => 'medalControlMostAdvantage',
            'gangsallhere' => 'medalCountdownRoundAllAlive',
            'thecycle' => 'medalCycle',
            'dodgethis' => 'medalDefeatHunterDodge',
            'barricadebreaker' => 'medalDefeatTitanBrace',
            'riftbreaker' => 'medalDefeatWarlockSigil',
            'notonmywatch' => 'medalDefense',
            'crushedthem' => 'medalMatchBlowout',
            'fightme' => 'medalMatchMostDamage',
            'timeandahalf' => 'medalMatchOvertime',
            'undefeated' => 'medalMatchUndefeated',
            'doubleplay' => 'medalMulti2x',
            'tripleplay' => 'medalMulti3x',
            'lightsout' => 'medalMulti4x',
            'annihilation' => 'medalMultiEntireTeam',
            'bestservedcold' => 'medalPayback',
            'quickstrike' => 'medalQuickStrike',
            'unyielding' => 'medalStreak10x',
            'ruthless' => 'medalStreak5x',
            'weranoutofmedals' => 'medalStreakAbsurd',
            'combinedfire' => 'medalStreakCombined',
            'shutdown' => 'medalStreakShutdown',
            'wreckingcrew' => 'medalStreakTeam',
            'notsofastmyfriend' => 'medalSuperShutdown',
            'mycrestismyown' => 'medalSupremacyNeverCollected',
            'safeandsecured' => 'medalSupremacySecureStreak',
            'survivor' => 'medalSurvivalUndefeated',
            'assaultspecialist' => 'medalWeaponAuto',
            'coldfusion' => 'medalWeaponFusion',
            'directhit' => 'medalWeaponGrenade',
            'hawkeye' => 'medalWeaponHandCannon',
            'lethalcadence' => 'medalWeaponPulse',
            'splashdamage' => 'medalWeaponRocket',
            'fieldscout' => 'medalWeaponScout',
            'closeencounters' => 'medalWeaponShotgun',
            'submachinist' => 'medalWeaponSmg',
            'regent' => 'medalWeaponSword',
            'neverindoubt' => 'medalMatchNeverTrailed',
            'fromthejawsofdefeat' => 'medalMatchComeback',
            'fallingstar' => 'medalAbilityDawnbladeSlam',
            'defyinggravity' => 'medalAbilityDawnbladeAerial',
            'singularity' => 'medalAbilityVoidwalkerVortex',
            'fromdowntown' => 'medalAbilityVoidwalkerDistance',
            'thunderstruck' => 'medalAbilityStormcallerLandfall',
            'lightningstrike' => 'medalAbilityFlowwalkerQuick',
            'entangled' => 'medalAbilityNightstalkerTetherQuick',
            'longbow' => 'medalAbilityNightstalkerLongRange',
            'perfectguard' => 'medalAbilitySentinelWard',
            'flyingfortress' => 'medalAbilitySentinelCombo',
            'absoluteforce' => 'medalAbilityJuggernautSlam',
            'strikerspecial' => 'medalAbilityJuggernautCombo',
            'pitchperfect' => 'medalAbilitySunbreakerLongRange',
            'everythinglookslikeanail' => 'medalAbilitySunbreakerMulti',
            'counterattack' => 'medalCountdownDefense',
            'pyrotechnics' => 'medalCountdownDetonated',
            'bombswhatbombs' => 'medalCountdownDefusedMulti',
            'laststand' => 'medalCountdownDefusedLastStand',
            'perfectgame' => 'medalCountdownPerfect',
            'lonegun' => 'medalSurvivalWinLastStand',
            'minutetowinit' => 'medalSurvivalQuickWipe',
            'undertaker' => 'medalSurvivalKnockout',
            'accordingtoplan' => 'medalSurvivalComeback',
            'untouchable' => 'medalSurvivalTeamUndefeated',
            'reclaimer' => 'medalControlPerimeterKill',
            'dominantadvantage' => 'medalControlAdvantageStreak',
            'poweroverwhelming' => 'medalControlPowerPlayWipe',
            'firstsecure' => 'medalSupremacyFirstCrest',
            'steadfastally' => 'medalSupremacyRecoverStreak',
            'crestfallen' => 'medalSupremacyCrestCreditStreak',
            'acrownofcrests' => 'medalSupremacyPerfectSecureRate',
            'lightemup' => 'medalMayhemFirstSuper',
            'fireinthehole' => 'medalMayhemGrenadeStreak',
            'punchandpie' => 'medalMayhemMeleeStreak',
            'superstar' => 'medalMayhemCastStreak',
            'byourpowerscombined' => 'medalMayhemCastMulti',
            'totalmayhem' => 'medalMayhemKillStreak',
            'polyarmory' => 'medalCrimsonWeaponCombo',
            'thirdwheel' => 'medalCrimsonRevengeMulti',
            'brokenup' => 'medalCrimsonApartMulti',
            'heartbreaker' => 'medalCrimsonSuddenDeath',
            'bestinclass' => 'medalRumbleDefeatAllClasses',
            'assassin' => 'medalRumbleUnassistedStreak',
            'pickpocket' => 'medalRumbleStealStreak',
            'podiumfinish' => 'medalRumbleTop3',
            'roundrobin' => 'medalRumbleDefeatAllPlayers',
            'thesumofalltears' => 'medalRumbleBetterThanAllCombined',
            'slayer' => 'medalSlayer',
            'reaper' => 'medalStreak6x',
            'seventhcolumn' => 'medalStreak7x',
            'localmaxima' => 'medalShowdownMostKills',
            'denialofservice' => 'medalShowdownAmmoStreak',
            'clawingback' => 'medalShowdownRetakeLead',
            'whenthedustclears' => 'medalShowdownFullTeamSurvival',
            'werenotdoneyet' => 'medalShowdownForceFinalRound',
            'invincible' => 'medalShowdownUndefeated',
            'totalmedals' => 'allMedalsEarned',
            'armyofone' => 'medals_pvecomp_medal_invader_kill_four',
            'massacre' => 'medals_pvecomp_medal_massacre',
            'noescape' => 'medals_pvecomp_medal_no_escape',
            'blockbuster' => 'medals_pvecomp_medal_blockbuster',
            'motehavebeen' => 'medals_pvecomp_medal_tags_denied_15',
            'denied' => 'medals_pvecomp_medal_denied',
            'gbnotonmywatch' => 'medals_pvecomp_medal_invasion_shutdown',
            'locksmith' => 'medals_pvecomp_medal_locksmith',
            'blockparty' => 'medals_pvecomp_medal_block_party',
            'neversaydie' => 'medals_pvecomp_medal_never_say_die',
            'halfbanked' => 'medals_pvecomp_medal_half_banked',
            'takingturns' => 'medals_pvecomp_medal_everyone_invaded',
            'killmonger' => 'medals_pvecomp_medal_killmonger',
            'thrillmonger' => 'medals_pvecomp_medal_thrillmonger',
            'overkillmonger' => 'medals_pvecomp_medal_overkillmonger',
            'valuehunter' => 'medals_pvecomp_medal_value_hunter',
            'firsttoblock' => 'medals_pvecomp_medal_first_to_block',
            'fastfill' => 'medals_pvecomp_medal_fast_fill',
            'biggamehunter' => 'medals_pvecomp_medal_big_game_hunter',
            'payback' => 'medals_pvecomp_medal_revenge',
            'rapidpayback' => 'medals_pvecomp_medal_revenge_same_invasion',
            'titansmash' => 'medals_pvecomp_medal_fist_of_havoc_multikill',
            'atitancanfly' => 'medals_pvecomp_medal_meteor_strike_multikill',
            'wardofdawn' => 'medals_pvecomp_medal_ward_of_dawn_blocking',
            'captainofthevoid' => 'medals_pvecomp_medal_void_shield_multikill',
            'atimeforhammers' => 'medals_pvecomp_medal_thermal_hammer_multikill',
            'burningpath' => 'medals_pvecomp_medal_thermal_maul_multikill',
            'lightningrod' => 'medals_pvecomp_medal_arc_staff_multikill',
            'fireslinger' => 'medals_pvecomp_medal_golden_gun_multikill',
            'fanofknives' => 'medals_pvecomp_medal_thermal_knives_multikill',
            'spectralsurgeon' => 'medals_pvecomp_medal_void_blade_multikill',
            'ensnarement' => 'medals_pvecomp_medal_void_bow_multikill',
            'ridelightning' => 'medals_pvecomp_medal_arc_lightning_multikill',
            'chaosincarnate' => 'medals_pvecomp_medal_arc_beam_multikill',
            'voidbaseddemolition' => 'medals_pvecomp_medal_nova_bomb_multikill',
            'voidunleashed' => 'medals_pvecomp_medal_nova_pulse_multikill',
            'rainoffire' => 'medals_pvecomp_medal_thermal_sword_multikill',
            'dugin' => 'Medals_pvecomp_medal_thermal_sword_healing_multikill',
        ];
    }

    /**
     * Get medal command keys that should resolve against Gambit activity modes.
     */
    public static function gambitKeys(): array
    {
        return [
            'armyofone', 'massacre', 'noescape', 'blockbuster', 'motehavebeen', 'denied', 'gbnotonmywatch',
            'locksmith', 'blockparty', 'neversaydie', 'halfbanked', 'takingturns', 'killmonger', 'thrillmonger',
            'overkillmonger', 'valuehunter', 'firsttoblock', 'fastfill', 'biggamehunter', 'payback',
            'rapidpayback', 'titansmash', 'atitancanfly', 'wardofdawn', 'captainofthevoid', 'atimeforhammers',
            'burningpath', 'lightningrod', 'fireslinger', 'fanofknives', 'spectralsurgeon', 'ensnarement',
            'ridelightning', 'chaosincarnate', 'voidbaseddemolition', 'voidunleashed', 'rainoffire', 'dugin',
        ];
    }
}
